# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'

      # Add auth
      - run: git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com" && git config --local user.name "GitHub Action"

      # Checkout gh-pages
      - name: Checkout gh-pages
        run: git checkout --orphan gh-pages

      # Begin node work
      - name: Install node modules
        run: npm install

      # Build the dist directory
      - name: Start the build
        run: npm run build

      # Add, commit and push
      - name: Add, commit and push
        run: git --work-tree dist add --all
      - name: Commiting
        run: git --work-tree dist commit -m "gh-pages deployment"
      - name: Pushing
        run: git push origin HEAD:gh-pages --force
